# Generated by Django 6.0.2 on 2026-02-16 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='momo',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.category'),
        ),
    ]
