# Generated by Django 6.0.2 on 2026-02-23 04:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_emailverfication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testemonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('customer_type', models.CharField(choices=[('regular', 'Regular Customer'), ('new', 'New Customer'), ('vip', 'VIP Customer')], max_length=20)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('review', models.TextField()),
                ('is_most_helpful', models.BooleanField(default=False)),
                ('visited_date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
